package Exception;

public class sample_8 
{
	   public static void main(String[] args) 
	   {
		     int a = 10;
		     int b = 0;
		     int c = 0;
		     
		     System.out.println(c);
		     
		     try
		     {
                      c= a/b;
		     }
        	catch (ArithmeticException aa)
        	{
		            System.out.println("ArithmeticException ");
	
	       }
	
	
	            System.out.println("gm");
	            System.out.println("hii ");
	
	
	
	
   }
}
